#!/bin/sh

set -e

_REPLFWDCONF=replfwd.conf

REPLFWDCONF_SOURCE="/usr/share/wforce-replfwd/${_REPLFWDCONF}"
REPLFWDCONF="/etc/wforce/${_REPLFWDCONF}"

case "$1" in
  configure)
    UCF_FORCE_CONFFMISS=1 \
        ucf --three-way --debconf-ok \
        "${REPLFWDCONF_SOURCE}" "${REPLFWDCONF}"
    ucfr wforce-replfwd "${REPLFWDCONF}"

    # Now that the file is recorded, let's change the creds by one-time
    # generated ones
    if grep -q -e '--WEBPWD' -e '--SETKEY' "${REPLFWDCONF}"; then
        SETKEY=$(replfwd -k)
        WEBPWD=$(dd if=/dev/urandom bs=1 count=32 2>/dev/null |
            base64 | rev | cut -b 2-14 | rev)

        if [ -z "${SETKEY}" ] || [ -z "${WEBPWD}" ]; then
            echo "Unable to generate credentials for ${REPLFWDCONF}" >&2
            exit 1
        fi

        sed -e "s#--WEBPWD#${WEBPWD}#g" \
            -e "s#--SETKEY#${SETKEY}#g" \
            -i "${REPLFWDCONF}"
    else
        status=$?
        [ "${status}" -eq 1 ] || exit "${status}"
    fi

    chmod 0640 "${REPLFWDCONF}"
    chown wforce:wforce "${REPLFWDCONF}"
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

# Init script has errors in previous versions. Postinst script should just
# return the exit status of this script
initscript_error() {
	return $1
}

#DEBHELPER#

exit 0
