webserver("0.0.0.0:8087", "super")
setKey("d6ZYYP/nSXQwfoSOgbcJSTE3zPe6Ty3KRRNixBfysA0=")

addACL("127.0.0.0/8")
addACL("192.168.0.0/16")

setSiblingsWithKey({{"127.0.0.1:4002", "2ZOQKjEtAKCKqB1TiaDAtGbe45kYUkQ7emqaBwcHmxI="}})

setReplicationForwarderSrcs({"127.0.0.1"})
setReplicationForwarderDestsWithKey({{"127.0.0.1:8001", "Ay9KXgU3g4ygK+qWT0Ut4gH8PPz02gbtPeXWPdjD0HE=", "true", "true"}})

siblingListener("0.0.0.0:8002")
