addListener("0.0.0.0:8086", false, "", "", {})
setWebserverPassword("super")
setKey("Ay9KXgU3g4ygK+qWT0Ut4gH8PPz02gbtPeXWPdjD0HE=")

addACL("127.0.0.0/8")
addACL("192.168.0.0/16")

addSiblingWithKey("127.0.0.1:4001", "qjShDn9gnCunXSH5quIXoNzrduomuTomWpvoePzi434=")

addReplicationForwarderSrc("127.0.0.1")
addReplicationForwarderDestWithKey("127.0.0.1:8002", "d6ZYYP/nSXQwfoSOgbcJSTE3zPe6Ty3KRRNixBfysA0=", true, true)

siblingListener("0.0.0.0:8001")
