webserver("0.0.0.0:8085", "super")
setKey("2ZOQKjEtAKCKqB1TiaDAtGbe45kYUkQ7emqaBwcHmxI=")
controlSocket("0.0.0.0:4105")

setSiblingsWithKey({{"127.0.0.1:4002", ""}, {"127.0.0.1:8002", "d6ZYYP/nSXQwfoSOgbcJSTE3zPe6Ty3KRRNixBfysA0="}})
siblingListener("0.0.0.0:4002")

dofile("./wforce-tw.conf")