webserver("0.0.0.0:8084", "super")
setKey("qjShDn9gnCunXSH5quIXoNzrduomuTomWpvoePzi434=")
controlSocket("0.0.0.0:4104")

addSibling("127.0.0.1:4001");
addSiblingWithKey("127.0.0.1:8001:tcp", "Ay9KXgU3g4ygK+qWT0Ut4gH8PPz02gbtPeXWPdjD0HE=");
siblingListener("0.0.0.0:4001")

dofile("./wforce-tw.conf")