{
 "title": "Abuse Shield Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Responses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Allow Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(status) (rate(wforce_allow_status_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allow Response Breakdown",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (wforce_allow_status_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Blocklists & Whitelists", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Blocklist Entries",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(type) (wforce_bl_entries)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Whitelist Entries",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(type) (wforce_wl_entries)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocklist Entries over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by(type) (wforce_bl_entries)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Whitelist Entries over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum by(type) (wforce_wl_entries)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Response Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }, "repeat": "env" },
  {
   "title": "Wforce Response duration - Heat map",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by(le) (rate(wforce_worker_response_duration_seconds_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS Query Response",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum by(le) (rate(wforce_dns_query_response_seconds_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true
  },
  {
   "title": "DNS query response",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(resolver) (rate(wforce_dns_query_response_seconds_sum[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS Queries Count",
   "type": "timeseries",
   "description": "# HELP wforce_dns_queries_total How many DNS queries were performed?\n# TYPE wforce_dns_queries_total counter",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "sum by(resolver) (rate(wforce_dns_queries_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Commands and response duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Commands",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum by(cmd) (rate(wforce_commands_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sum of replication sent by status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "sum by(status) (rate(wforce_replication_sent_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WebHook Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum by(url) (rate(wforce_webhook_events_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WebHook Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    { "expr": "wforce_web_queue_size", "legendFormat": "{{__name__}}{pod={{pod}}}" }
   ]
  },
  {
   "title": "Active HTTP Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "targets": [
    { "expr": "wforce_active_http_connections", "legendFormat": "__auto" }
   ]
  }
 ]
}