# First do the source builds
@INCLUDE Dockerfile.target.sdist

# This defines the dstribution base layer
# Put only the bare minimum of common commands here, without dev tools
FROM centos:7 as dist-base
RUN yum install -y epel-release centos-release-scl

# Do the actual rpm build
@INCLUDE Dockerfile.rpmbuild


