@EXEC export BUILDER_RHEL_VERSION=2023
@EXEC export BUILDER_RHEL_FLAVOUR=amazon
# First do the source builds
@INCLUDE Dockerfile.target.sdist

# This defines the distribution base layer
# Put only the bare minimum of common commands here, without dev tools
FROM amazonlinux:2023 as dist-base
RUN yum install -y clang clang-devel llvm llvm-devel boost-devel wget tar gzip make

# Do the actual rpm build
@INCLUDE Dockerfile.rpmbuild
