#!/usr/bin/env python
#
# Shell-script style.

import os
import requests
import shutil
import subprocess
import sys
import tempfile
import time
import signal

WEBPORT = '8084'
APIKEY = 'super'

ACL_LIST_TPL = """
# Generated by runtests.py
# local host
127.0.0.1
::1
"""

wait = ('--wait' in sys.argv)
if wait:
    sys.argv.remove('--wait')

wfcmd1 = ("wforce -s -C ./wforce1.conf").split()
wfcmd2 = ("wforce -s -C ./wforce2.conf").split()
rfcmd1 = ("replfwd -C ./replfwd1.conf").split()
rfcmd2 = ("replfwd -C ./replfwd2.conf").split()

# Now run the tests.
print("Launching commands...")
print(' '.join(wfcmd1))
print(' '.join(wfcmd2))
print(' '.join(rfcmd1))
print(' '.join(rfcmd2))
wfproc1 = subprocess.Popen(wfcmd1, close_fds=True)
wfproc2 = subprocess.Popen(wfcmd2, close_fds=True)
rfproc1 = subprocess.Popen(rfcmd1, close_fds=True)
rfproc2 = subprocess.Popen(rfcmd2, close_fds=True)

def sighandler(signum, frame):
    wfproc1.terminate()
    wfproc1.wait()
    wfproc2.terminate()
    wfproc2.wait()
    rfproc1.terminate()
    rfproc1.wait()
    rfproc2.terminate()
    rfproc2.wait()
    subprocess.call(["/bin/stty", "sane"])

signal.signal(signal.SIGINT, sighandler)

print("Waiting for wforce webserver port to become available...")
available = False
for port in [ '8084', '8085', '8086', '8087']:
    for try_number in range(0, 10):
        try:
            res = requests.get('http://127.0.0.1:%s/' % port)
            available = True
            break
        except:
            time.sleep(0.5)

    if not available:
        print("Webserver port %s not reachable after 10 tries, giving up." % port)
        sighandler(signal.SIGINT, None)
        sys.exit(2)

    available = False

print(subprocess.run(['ps', '-ef'], stdout=subprocess.PIPE).stdout.decode('utf-8'))
        
print("Running tests...")
rc = 0
test_env = {}
test_env.update(os.environ)
test_env.update({'WEBPORT': WEBPORT, 'APIKEY': APIKEY})

try:
    print("")
    if len(sys.argv) > 1:
        p = subprocess.check_call(["pytest", "--junitxml", sys.argv[1]], env=test_env)
    else:
        p = subprocess.check_call(["pytest", "--junitxml", "pytest.xml"], env=test_env)
except subprocess.CalledProcessError as ex:
    rc = ex.returncode
finally:
    if wait:
        print("Waiting as requested, press ENTER to stop.")
        raw_input()
    sighandler(signal.SIGINT, None)

subprocess.call(["/bin/stty", "sane"])
    
sys.exit(rc)
