version: '2'
services:
  wforce_image:
    image: powerdns/wforce:${VERSION}
    build:
      context: weakforced
      dockerfile: docker/wforce_image/Dockerfile
      args:
        - license=${LICENSE}
        - git_revision=${GIT_REVISION}
        - version=${VERSION}
        - MAXMIND_LICENSE_KEY=${MAXMIND_LICENSE_KEY}
    environment:
      - WFORCE_VERBOSE
      - WFORCE_HTTP_PORT=${WFORCE_PORT}
      - WFORCE_HTTP_PASSWORD=${WFORCE_PASSWORD}
      - WFORCE_LOGSTASH_URL
      - WFORCE_CONFIG_FILE
    ports:
      - "${WFORCE_PORT}:${WFORCE_PORT}"
  wforce_minimal:
    image: powerdns/wforce-minimal:${VERSION}
    build:
      context: weakforced
      dockerfile: docker/wforce_image/Dockerfile.minimal
      args:
        - license=${LICENSE}
        - git_revision=${GIT_REVISION}
        - version=${VERSION}
  trackalert:
    image: powerdns/wforce:${VERSION}
    environment:
      - TRACKALERT=1
      - TRACKALERT_HTTP_PORT=${TRACKALERT_PORT}
      - TRACKALERT_HTTP_PASSWORD=${WFORCE_PASSWORD}
    ports:
      - "${TRACKALERT_PORT}:${TRACKALERT_PORT}"